# Generated by Django 3.0.8 on 2020-07-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_name', models.CharField(max_length=50, verbose_name='Аллергент')),
            ],
            options={
                'verbose_name': 'Аллергент',
                'verbose_name_plural': 'Аллергенты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Название')),
                ('energy', models.PositiveSmallIntegerField(default=0, help_text='Укажите калорийность на порцию в кКал', verbose_name='Калорийность')),
                ('protein', models.PositiveSmallIntegerField(default=0, help_text='Укажите количество белка на порцию в граммах', verbose_name='Белки')),
                ('fat', models.PositiveSmallIntegerField(default=0, help_text='Укажите количество жиров на порцию в граммах', verbose_name='Жиры')),
                ('carbohydrates', models.PositiveSmallIntegerField(default=0, help_text='Укажите количество углеводов на порцию в граммах', verbose_name='Углеводы')),
                ('price', models.PositiveSmallIntegerField(default=0, help_text='Укажите цену в рублях', verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/dish_images/', verbose_name='Изображение')),
                ('allergens', models.ManyToManyField(blank=True, to='menu.Allergen', verbose_name='Аллергенты')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
